#define FUNC0(_fn, _ret)  COPY_ON_SUC(proc, fnlist_ptr->p ## _fn, GetProcAddress(lib, #_fn));
#define FUNC1(_fn, _ret)  FUNC0(_fn, _ret)
#define FUNC2(_fn, _ret)  FUNC0(_fn, _ret)
#define FUNC3(_fn, _ret)  FUNC0(_fn, _ret)
#define FUNC4(_fn, _ret)  FUNC0(_fn, _ret)
#define FUNC5(_fn, _ret)  FUNC0(_fn, _ret)
#define FUNC6(_fn, _ret)  FUNC0(_fn, _ret)
#define FUNC7(_fn, _ret)  FUNC0(_fn, _ret)
#define FUNC8(_fn, _ret)  FUNC0(_fn, _ret)
#define FUNC9(_fn, _ret)  FUNC0(_fn, _ret)
#define FUNC10(_fn, _ret) FUNC0(_fn, _ret)
#define FUNC11(_fn, _ret) FUNC0(_fn, _ret)
#define FUNC12(_fn, _ret) FUNC0(_fn, _ret)
#define FUNC13(_fn, _ret) FUNC0(_fn, _ret)
#define FUNC14(_fn, _ret) FUNC0(_fn, _ret)
#define FUNC15(_fn, _ret) FUNC0(_fn, _ret)
